### PR TITLE
Adds extra optional argument headers

### LINKED ISSUE #8: Add option to pass extra body headers
I need to add extra body headers, exactly as this [fork](https://github.com/babashka/http-server/compare/main...russmatney:http-server:main) 

Would you be interested in a PR adding headers as an extra optional argument where you can pass a map with extra body headers to be merged with the current one?

### PR DESCRIPTION
**Pull request by rafaeldelboni**
Closes: https://github.com/babashka/http-server/issues/8
Related to: https://github.com/babashka/http-server/issues/7

### CODE REVIEW

**Comment by rafaeldelboni** [comment]
I don't know if you want me to bump `version.edn` file as well and sorry for any ugly code :)

**Comment by borkdude** [comment]
I don't think the `test` folder requires another `.clj-kondo` directory

**Comment by borkdude** [comment]
One problem with the string + split way of doing things on the CLI is that headers can start with colons and these would be parsed as the next option. I think coercing the headers as `:edn` might make more sense in this case?

**Comment by rafaeldelboni** [comment]
Sure, makes sense

**Comment by rafaeldelboni** [comment]
@borkdude could you check if my change makes sense?

**Comment by borkdude** [comment]
Looks good to me!

**Pull request merged**
